# Generated by Django 4.0.3 on 2022-04-02 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiren', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swords',
            old_name='sword',
            new_name='name',
        ),
    ]
