# Generated by Django 4.0.3 on 2022-04-15 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiren', '0003_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrolls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiren.prices')),
            ],
        ),
    ]
