# Generated by Django 4.0.3 on 2022-04-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotomoto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='for_sale',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
